# Generated by Django 4.2.1 on 2023-07-01 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TabEstatus',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_nomb', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tab_estatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabGrupo',
            fields=[
                ('grup_id', models.AutoField(primary_key=True, serialize=False)),
                ('grup_nom', models.CharField(max_length=150)),
                ('grup_fechac', models.DateField()),
                ('grup_fechat', models.DateField()),
                ('grup_desc', models.TextField(blank=True, null=True)),
                ('grup_integrante', models.IntegerField()),
            ],
            options={
                'db_table': 'tab_grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabInstitucion',
            fields=[
                ('ins_id', models.AutoField(primary_key=True, serialize=False)),
                ('ins_nomb', models.CharField(max_length=255)),
                ('ins_sigla', models.CharField(blank=True, max_length=20, null=True)),
                ('ins_dir', models.CharField(max_length=150)),
                ('ins_localidad', models.CharField(max_length=50)),
                ('ins_tel', models.CharField(max_length=10)),
                ('ins_correo', models.CharField(max_length=100)),
                ('ins_subcat', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'tab_institucion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabMconsejo',
            fields=[
                ('mcon_id', models.AutoField(primary_key=True, serialize=False)),
                ('mcon_nomb', models.CharField(max_length=50)),
                ('mcon_app', models.CharField(max_length=30)),
                ('mcon_apm', models.CharField(max_length=30)),
                ('mcon_tel', models.CharField(max_length=10)),
                ('mcon_correo', models.CharField(max_length=60)),
                ('mcon_correo2', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'tab_mconsejo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabMiembro',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_curp', models.CharField(blank=True, max_length=13, null=True)),
                ('m_nomb', models.CharField(max_length=50)),
                ('m_app', models.CharField(max_length=50)),
                ('m_apm', models.CharField(max_length=30)),
                ('m_tel', models.CharField(max_length=10)),
                ('m_tel2', models.CharField(blank=True, max_length=10, null=True)),
                ('m_correo', models.CharField(max_length=80)),
                ('m_correo2', models.CharField(blank=True, max_length=80, null=True)),
                ('m_cargo', models.CharField(max_length=100)),
                ('m_fechains', models.DateField()),
                ('m_genero', models.IntegerField()),
                ('m_gradacad', models.IntegerField()),
                ('m_estatus', models.IntegerField()),
                ('m_fkinst', models.ForeignKey(db_column='m_fkinst', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodos.tabinstitucion')),
            ],
            options={
                'db_table': 'tab_miembro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabProyecto',
            fields=[
                ('proy_id', models.AutoField(primary_key=True, serialize=False)),
                ('proy_nomb', models.CharField(max_length=255)),
                ('proy_tipo', models.CharField(max_length=15)),
                ('proy_desc', models.TextField()),
                ('proy_fechini', models.DateField()),
                ('proy_fechfin', models.DateField()),
                ('proy_coord', models.ForeignKey(db_column='proy_coord', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmconsejo')),
                ('proy_estatus', models.ForeignKey(db_column='dp_fkestatus', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabestatus')),
            ],
            options={
                'db_table': 'tab_proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabTipoacuerdo',
            fields=[
                ('tipa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipa_nomb', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tab_tipoacuerdo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabTipodependencia',
            fields=[
                ('tipodep_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipodep_nomb', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tab_tipodependencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabTiporeunion',
            fields=[
                ('tipreu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipreu_nomb', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tab_tiporeunion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabTipousuario',
            fields=[
                ('tip_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_nomb', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tab_tipousuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabReunion',
            fields=[
                ('reu_id', models.AutoField(primary_key=True, serialize=False)),
                ('reu_cod', models.CharField(db_comment='CODIGO DE LA REUNION', max_length=10)),
                ('reu_nomb', models.CharField(blank=True, db_comment='NOMBRE DE LA REUNION', max_length=255, null=True)),
                ('reu_participante', models.IntegerField(db_comment='CANTIDAD DE PARTICIPANTES EN LA REUNIËN')),
                ('reu_obs', models.TextField(db_comment='DESCRIPCION DE LA REUNION')),
                ('reu_medio', models.CharField(max_length=100)),
                ('reu_fecha', models.DateField()),
                ('reu_fkcoor', models.ForeignKey(db_column='reu_fkcoor', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmconsejo')),
                ('reu_fkgrup', models.ForeignKey(db_column='reu_fkgrup', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabgrupo')),
                ('reu_fkproyect', models.ForeignKey(db_column='reu_fkproyect', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabproyecto')),
                ('reu_fktipo', models.ForeignKey(db_column='reu_fktipo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtiporeunion')),
            ],
            options={
                'db_table': 'tab_reunion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabProyectoProyMiemb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tabmiembro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro')),
                ('tabproyecto', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabproyecto')),
            ],
            options={
                'db_table': 'tab_proyecto_proy_miemb',
                'managed': True,
                'unique_together': {('tabproyecto', 'tabmiembro')},
            },
        ),
        migrations.AddField(
            model_name='tabproyecto',
            name='proy_miemb',
            field=models.ManyToManyField(through='nodos.TabProyectoProyMiemb', to='nodos.tabmiembro'),
        ),
        migrations.AddField(
            model_name='tabmiembro',
            name='m_fktipo',
            field=models.ForeignKey(db_column='m_fktipo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtipousuario'),
        ),
        migrations.AddField(
            model_name='tabmiembro',
            name='m_fkuser',
            field=models.ForeignKey(db_column='m_fkuser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabmconsejo',
            name='mcon_fktipou',
            field=models.ForeignKey(db_column='mcon_fktipou', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtipousuario'),
        ),
        migrations.AddField(
            model_name='tabinstitucion',
            name='ins_fkenlace',
            field=models.ForeignKey(blank=True, db_column='ins_fkenlace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro'),
        ),
        migrations.AddField(
            model_name='tabinstitucion',
            name='ins_fktipo',
            field=models.ForeignKey(db_column='ins_fktipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtipodependencia'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fkcoord',
            field=models.ForeignKey(db_column='grup_fkcoord', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodos.tabmconsejo'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fkenlace',
            field=models.ForeignKey(db_column='grup_fkenlace', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodos.tabmiembro'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fkest',
            field=models.ForeignKey(db_column='grup_fkest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodos.tabestatus'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fkproyecto',
            field=models.ForeignKey(db_column='grup_fkproyecto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodos.tabproyecto'),
        ),
        migrations.CreateModel(
            name='TabDescreunion',
            fields=[
                ('desr_id', models.AutoField(primary_key=True, serialize=False)),
                ('desr_fkmiem', models.ForeignKey(db_column='desr_fkmiem', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro')),
                ('desr_fkreu', models.ForeignKey(db_column='desr_fkreu', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabreunion')),
            ],
            options={
                'db_table': 'tab_descreunion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabDescgrupo',
            fields=[
                ('dg_id', models.AutoField(primary_key=True, serialize=False)),
                ('dg_fkgrupo', models.ForeignKey(db_column='dg_fkgrupo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabgrupo')),
                ('dg_fkmiemb', models.ForeignKey(db_column='dg_fkmiemb', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro')),
            ],
            options={
                'db_table': 'tab_descgrupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TabAcuerdoreunion',
            fields=[
                ('acu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('acu_cod', models.CharField(max_length=15)),
                ('acu_fcompromiso', models.DateField()),
                ('acu_fkestatus', models.ForeignKey(db_column='acu_fkestatus', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabestatus')),
                ('acu_fkreunion', models.ForeignKey(db_column='acu_fkreunion', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabreunion')),
                ('acu_fktipo', models.ForeignKey(db_column='acu_fktipo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtipoacuerdo')),
            ],
            options={
                'db_table': 'tab_acuerdoreunion',
                'managed': True,
            },
        ),
    ]
