# Generated by Django 4.2.1 on 2023-05-23 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabDependencia',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_nomb', models.CharField(max_length=100)),
                ('dep_siglas', models.CharField(max_length=10)),
                ('dep_direccon', models.CharField(max_length=150)),
                ('dep_localidad', models.CharField(max_length=50)),
                ('dep_tel', models.CharField(max_length=10)),
                ('dep_correo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tab_dependencia',
            },
        ),
        migrations.CreateModel(
            name='TabEstatus',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_nomb', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tab_estatus',
            },
        ),
        migrations.CreateModel(
            name='TabGrupo',
            fields=[
                ('grup_id', models.AutoField(primary_key=True, serialize=False)),
                ('grup_nom', models.CharField(max_length=150)),
                ('grup_fechac', models.DateField()),
                ('grup_fechat', models.DateField()),
                ('grup_desc', models.TextField(blank=True, null=True)),
                ('grup_integrante', models.IntegerField()),
            ],
            options={
                'db_table': 'tab_grupo',
            },
        ),
        migrations.CreateModel(
            name='TabMconsejo',
            fields=[
                ('mcon_id', models.AutoField(primary_key=True, serialize=False)),
                ('mcon_nomb', models.CharField(max_length=50)),
                ('mcon_app', models.CharField(max_length=30)),
                ('mcon_apm', models.CharField(max_length=30)),
                ('mcon_tel', models.CharField(max_length=10)),
                ('mcon_correo', models.CharField(max_length=60)),
                ('mcon_correo2', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'tab_mconsejo',
            },
        ),
        migrations.CreateModel(
            name='TabMiembro',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_nomb', models.CharField(max_length=50)),
                ('m_app', models.CharField(max_length=50)),
                ('m_apm', models.CharField(max_length=30)),
                ('m_curp', models.CharField(blank=True, max_length=18, null=True)),
                ('m_tel', models.CharField(max_length=10)),
                ('m_tel2', models.CharField(blank=True, max_length=10, null=True)),
                ('m_correo', models.CharField(max_length=80)),
                ('m_correo2', models.CharField(blank=True, max_length=80, null=True)),
                ('m_cargo', models.CharField(max_length=100)),
                ('m_fechains', models.DateField()),
                ('m_genero', models.IntegerField()),
                ('m_gradacad', models.IntegerField()),
                ('m_estatus', models.IntegerField()),
                ('m_fkinst', models.ForeignKey(db_column='m_fkinst', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabdependencia')),
            ],
            options={
                'db_table': 'tab_miembro',
            },
        ),
        migrations.CreateModel(
            name='TabProyecto',
            fields=[
                ('proy_id', models.AutoField(primary_key=True, serialize=False)),
                ('proy_nomb', models.CharField(max_length=25)),
                ('proy_tipo', models.CharField(max_length=15)),
                ('proy_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('proy_fechini', models.DateField()),
                ('proy_fechfin', models.DateField()),
                ('proy_coord', models.ForeignKey(db_column='proy_coord', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro')),
                ('proy_sec', models.ForeignKey(db_column='proy_sec', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmconsejo')),
            ],
            options={
                'db_table': 'tab_proyecto',
            },
        ),
        migrations.CreateModel(
            name='TabTipodependencia',
            fields=[
                ('tipodep_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipodep_nomb', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tab_tipodependencia',
            },
        ),
        migrations.CreateModel(
            name='TabTiporeunion',
            fields=[
                ('tipreu_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipreu_nomb', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tab_tiporeunion',
            },
        ),
        migrations.CreateModel(
            name='TabTipousuario',
            fields=[
                ('tip_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_nomb', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tab_tipousuario',
            },
        ),
        migrations.CreateModel(
            name='TabReuniong',
            fields=[
                ('reu_id', models.AutoField(primary_key=True, serialize=False)),
                ('reu_nomb', models.CharField(blank=True, max_length=255, null=True)),
                ('reu_participante', models.IntegerField()),
                ('reu_obs', models.TextField()),
                ('reu_plat', models.CharField(max_length=100)),
                ('reu_fecha', models.DateField()),
                ('reu_fkgrup', models.ForeignKey(blank=True, db_column='reu_fkgrup', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabgrupo')),
                ('reu_fkproyect', models.ForeignKey(db_column='reu_fkproyect', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabproyecto')),
                ('reu_fktipo', models.ForeignKey(db_column='reu_fktipo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtiporeunion')),
            ],
            options={
                'db_table': 'tab_reuniong',
            },
        ),
        migrations.AddField(
            model_name='tabmiembro',
            name='m_fktipo',
            field=models.ForeignKey(db_column='m_fktipo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtipousuario'),
        ),
        migrations.AddField(
            model_name='tabmiembro',
            name='m_fkuser',
            field=models.ForeignKey(db_column='m_fkuser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tabmconsejo',
            name='mcon_fktipou',
            field=models.ForeignKey(db_column='mcon_fktipou', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtipousuario'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fkcoord',
            field=models.ForeignKey(db_column='grup_fkcoord', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fkenlace',
            field=models.ForeignKey(db_column='grup_fkenlace', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmconsejo'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fkest',
            field=models.ForeignKey(db_column='grup_fkest', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabestatus'),
        ),
        migrations.AddField(
            model_name='tabgrupo',
            name='grup_fknodo',
            field=models.ForeignKey(db_column='grup_fknodo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabproyecto'),
        ),
        migrations.CreateModel(
            name='TabDescreunion',
            fields=[
                ('desr_id', models.AutoField(primary_key=True, serialize=False)),
                ('desr_fkmiem', models.ForeignKey(db_column='desr_fkmiem', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro')),
                ('desr_fkreu', models.ForeignKey(db_column='desr_fkreu', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabreuniong')),
            ],
            options={
                'db_table': 'tab_descreunion',
            },
        ),
        migrations.CreateModel(
            name='TabDescproyec',
            fields=[
                ('dn_id', models.AutoField(primary_key=True, serialize=False)),
                ('dn_fkestatus', models.ForeignKey(db_column='dn_fkestatus', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabestatus')),
                ('dn_fkmiemb', models.ForeignKey(db_column='dn_fkmiemb', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro')),
                ('dn_fknodo', models.ForeignKey(db_column='dn_fknodo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabproyecto')),
            ],
            options={
                'db_table': 'tab_descproyec',
            },
        ),
        migrations.CreateModel(
            name='TabDescgrupo',
            fields=[
                ('dg_id', models.AutoField(primary_key=True, serialize=False)),
                ('dg_fkestatus', models.ForeignKey(db_column='dg_fkestatus', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabestatus')),
                ('dg_fkmiemb', models.ForeignKey(db_column='dg_fkmiemb', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro')),
                ('field_dg_fkgrupo', models.ForeignKey(db_column=' dg_fkgrupo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabgrupo')),
            ],
            options={
                'db_table': 'tab_descgrupo',
            },
        ),
        migrations.AddField(
            model_name='tabdependencia',
            name='dep_fkenlace',
            field=models.ForeignKey(blank=True, db_column='dep_fkenlace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabmiembro'),
        ),
        migrations.AddField(
            model_name='tabdependencia',
            name='dep_fktipo',
            field=models.ForeignKey(db_column='dep_fktipo', on_delete=django.db.models.deletion.DO_NOTHING, to='nodos.tabtipodependencia'),
        ),
    ]
