# Generated by Django 4.2.1 on 2023-07-01 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabinstitucion',
            name='ins_fktipo',
            field=models.ForeignKey(db_column='ins_fktipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nodos.tabtipodependencia'),
        ),
    ]
